// Map currency codes (lower case) to country codes (lower case) for FlagCDN
export const CURRENCY_TO_COUNTRY = {
  usd: 'us',
  eur: 'eu',
  gbp: 'gb',
  jpy: 'jp',
  aud: 'au',
  cad: 'ca',
  chf: 'ch',
  cny: 'cn',
  sek: 'se',
  nzd: 'nz',
  mxn: 'mx',
  sgd: 'sg',
  hkd: 'hk',
  nok: 'no',
  krw: 'kr',
  try: 'tr',
  inr: 'in',
  rub: 'ru',
  brl: 'br',
  zar: 'za',
  dkk: 'dk',
  pln: 'pl',
  thb: 'th',
  idr: 'id',
  huf: 'hu',
  czk: 'cz',
  ils: 'il',
  clp: 'cl',
  php: 'ph',
  aed: 'ae',
  cop: 'co',
  sar: 'sa',
  myr: 'my',
  ron: 'ro',
  ngn: 'ng',
  vnd: 'vn',
  ars: 'ar',
  pkr: 'pk',
  uah: 'ua',
  egp: 'eg',
  kes: 'ke',
  twd: 'tw',
};

// Fallback list of popular currencies to prioritize in dropdowns
export const POPULAR_CURRENCIES = [
  'usd', 'eur', 'gbp', 'jpy', 'aud', 'cad', 'chf', 'cny', 'inr', 'ngn'
];
